#!/bin/bash

ARDUINO_MINIMA="MINIMA"
ARDUINO_WIFI="UNOWIFIR4"
OPTA_DIGITAL="OPTA_DIGITAL"

#
# MINIMA
#

echo "EXECUTING SCRIPT FOR $ARDUINO_MINIMA"
./_private_fsp2arduino.sh $ARDUINO_MINIMA

#
# UNO WIFI
#

echo "EXECUTING SCRIPT FOR $ARDUINO_WIFI"
./_private_fsp2arduino.sh $ARDUINO_WIFI

#
# OPTA DIGITAL
#

echo "EXECUTING SCRIPT FOR $OPTA_DIGITAL"
./_private_fsp2arduino.sh $OPTA_DIGITAL
